<?php
/**
 * Created by PhpStorm.
 * User: Satyanarayan
 * Date: 24-04-2015
 * Time: 19:28
 */
?>
<style type="text/css">
    div.applied{
        float:left;
        background:#0098fe;
        z-index: 20000;
        font-weight: 400;
        color:#fff;
        padding:15px 10px;
        font-size:19px;

    }
    .opening-container{
        padding:20px;
    }
    .opening .top{
        height:20em;
        border:1px solid #000;
    }
    .opening .top .image{
        position: relative;
        height:100%;
        width:100%;
        background: url('<?php echo IMG_PATH; ?>fav-icon.png') #DDD;
        background-repeat: space;
    }
    .opening .top .price-tag{
        postion:absolute;
        padding: 15px 10px;
        font-size:19px;
        font-weight: 400;
        background: rgba(0,0,0,0.5);
        float:right;
        color:#ffffff;
    }

    .opening .top .opening-label{
        text-align: center;
        margin-top: 120px;
        position:absolute;
        width:100%;
        background: rgba(255,255,255,0.9);
    }

    .opening .top .opening-label .position{
        font-weight: bold;
        font-size:250%;
        color:#000;
    }
    .opening .top .opening-label .organization{
        font-weight: bold;
        font-size:120%;
        color:#000;
    }
    .opening-footer{
        padding:5px 0px;
    }
    .icon-footer-val{
        height:52px;
    }
    .footer-val{
        height:52px;
        /*border: 1px solid #000;*/
        padding:10px 5px;
        text-wrap: normal;
        text-align: left;
    }
    .opening-footer .container-fluid{
        padding:5px
    }
    .opening-footer{
        padding:0px;margin:0px;
    }
    .click{
        cursor: pointer;
    }

</style>

<div class="row">
    <!-- Job Container Begin -->
    <?php if(is_array($records)){ foreach($records as $record){?>
        <div class="col col-lg-4 col-md-4 col-sm-4 opening-container apply" rid="<?php echo $record->JOB_ID; ?>">

        <div class="opening">
            <div class="top">
                <div class="image">
                <div class="opening-label">
                    <div class="position<?php echo !$record->HAS_APPLIED?' click':'' ?>" rid="<?php echo $record->JOB_ID; ?>"><?php echo $record->JOB_TITLE; ?></div>
                    <div class="organization<?php echo !$record->HAS_APPLIED?' click':'' ?>" rid="<?php echo $record->JOB_ID; ?>"><?php echo $record->EMPLOYER_NAME; ?></div>
                </div>
                <div class="price-tag<?php echo !$record->HAS_APPLIED?' click':'' ?>" rid="<?php echo $record->JOB_ID; ?>"><?php echo $record->EMP_GET; ?>&euro;</div>
                <?php if ($record->HAS_APPLIED){ ?>
                    <div class="applied">Applied</div>
                <?php } ?>
                </div>
            </div>
        </div>
        <div class="opening-footer">
            <div class="container-fluid border center">
                <div class="row-fluid">
                    <div class="col col-lg-6 col-md-6 col-sm-12">
                        <div class="row">
                            <div class="col col-lg-6 col-md-4 col-sm-12 icon-footer-val "><img src="<?=IMG_PATH?>time.png"></div>
                            <div class="col col-lg-6 col-md-4 col-sm-12 footer-val center" style="text-align: center;" rid="<?php echo $record->JOB_ID; ?>"><?php echo $record->APPLY_LAST_DATE; ?></div>
                        </div>
                    </div>
                    <div class="col col-lg-6 col-md-6 col-sm-12">
                        <div class="row">
                            <div class="col col-lg-6 col-md-4 col-sm-12 icon-footer-val"><img src="<?=IMG_PATH?>place.png"></div>
                            <div class="col col-lg-6 col-md-4 col-sm-12 footer-val center" style="padding-top: 15px; text-align: center" rid="<?php echo $record->JOB_ID; ?>"><?php echo $record->POSTAL_CODE; ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
            $('.click').click(function(){
                var rid = $(this).attr('rid');
                bootbox.confirm('You are about to apply for the job <strong>"'+$('.position[rid="'+rid+'"]').text() +' at ' + $('.organization[rid="'+rid+'"]').text() +'</strong>". Proceed?',function(res){
                    if(res){
                        $.post('<?php echo SITE_PATH; ?>profile/applyforjob/',{'rid':rid},function(resp){
                            try {
                                var json_data = $.parseJSON(resp);
                                if(json_data.response.code=='0x0000'){
                                    window.location = window.location;
                                }else{
                                    bootbox.alert('Error while submitting Application for the job.');
                                }

                            }catch(err){bootbox.alert('Error while submitting Application for the job.');}
                        });
                    }
                });
            });
        })

    </script>
    <?php }}else{ ?>
    No Records....
    <?php } ?>
    <!-- Job Container End -->

</div>