<?php
/**
 * Created by PhpStorm.
 * User: Satyanarayan
 * Date: 22-05-2015
 * Time: 11:54
 */
?>
<div class="row">
    <!--div class="col-lg-12"><h3>Vaihtaminen Salasanan</h3></div-->
    <div class="col-lg-6 col-lg-offset-3">
        <form class="form-horizontal" id="password-reset-form">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">Käyttäjän ID</label>
                <div class="col-sm-9">
                    <input type="email" class="form-control" id="user_name" placeholder="User Name" value="<?php echo $this->session->user_data->usr_nm; ?>" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-3 control-label">Nykyinen salasana</label>
                <div class="col-sm-9">
                    <input type="password" class="form-control" id="current_password" placeholder="Nykyinen salasana">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-3 control-label">Uusi salasana</label>
                <div class="col-sm-9">
                    <input type="password" class="form-control" id="new_password" placeholder="Uusi salasana">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-3 control-label">Vahvistaa salasana</label>
                <div class="col-sm-9">
                    <input type="password" class="form-control" id="confirm_password" placeholder="Vahvistaa salasana">
                </div>
            </div>
            <div style="text-align:right">
                <button type="button" class="btn btn-success" id="change-password">Tallenna</button>
                <button type="reset" class="btn btn-default" id="reset-form">Asettaa uudelleen</button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        /*$('#confirm-password').blur(function(){

            var new_password = $('#new_password').val();
            var confirm_password = $('#confirm_password').val();

            if($.trim(new_password) != $.trim(confirm_password)){bootbox.alert('Uusi salasana ja vahvista salasana eivät ole samat',function(){$('#confirm_password').focus();});}
        });*/
        $('button#change-password').click(function(){
            var ele = $(this);

            var cur_password = $('#current_password').val();
            var new_password = $('#new_password').val();
            var confirm_password = $('#confirm_password').val();

            if($.trim(cur_password).length == 0) {bootbox.alert('Kirjoita Nykyinen salasana',function(){$('#current_password').focus();}); return false;}
            if($.trim(new_password).length == 0) {bootbox.alert('Kirjoita uusi salasana',function(){$('#new_password').focus();}); return false;}
            if($.trim(confirm_password).length == 0) {bootbox.alert('Kirjoita Vahvista salasana',function(){$('#confirm_password').focus();}); return false;}
            if($.trim(new_password) != $.trim(confirm_password)){bootbox.alert('Uusi salasana ja vahvista salasana eivät ole samat',function(){$('#confirm_password').focus();}); return false;}
            if($.trim(cur_password) == $.trim(new_password)){bootbox.alert('Uusi salasana ei voi olla sama kuin nykyinen salasana',function(){$('#new_password').focus();}); return false;}

            $.post('<?php echo SITE_PATH; ?>accounts/changepassword',{'c':cur_password,'n':new_password,'m':confirm_password},function(resp){
                    //CHECK POINT:
                    //bootbox.alert(resp,function(){ele.removeAttr('disabled');});
                    ele.attr('disabled','disabled');
                    try{
                        var json_data = $.parseJSON(resp);
                        if(json_data.response.code=='0x0000'){
                            bootbox.alert('Salasana Reset Onnistuneesti',function(){ele.removeAttr('disabled'); $('#reset-form').trigger('click');}).fadeOut(8000);
                        }else{
                            bootbox.alert(json_data.reposnse.resp_msg,function(){ele.removeAttr('disabled');});
                        }
                    }catch(err){
                        bootbox.alert('Salasanaa ei voi palauttaa tällä hetkellä... Yritä jonkin ajan kuluttua.',function(){ele.removeAttr('disabled');});
                    }
            });



        });
    });
</script>