<?php
/**
 * Created by PhpStorm.
 * User: Satyanarayan
 * Date: 07-05-2015
 * Time: 12:43
 */
?>
    <div class="footer-bg">
        <div class="container">
            <div class="page-wrapper">
                <div class="footer-nav">
                    <!--ul>
                        <li><a href="#">Tuki</a></li>
                        <li><a href="#">Käyttöehdot</a></li>
                        <li><a href="#">Usein kysyttyä</a></li>
                        <li><a href="#">Blogi</a></li>
                        <li><a href="#">Ota yhteyttä</a></li>
                    </ul-->
                </div>
                <div class="footer-logo"><img src="<?php echo SITE_PATH; ?>img/task-logo-footer.png" alt="Logo"></div>
                <div class="footer-copyrights">Copyright GoTaskU Oy 2015. Kaikki oikeudet pidätetään.</div>
            </div>
        </div>
    </div>
