<?php
/**
 * Created by PhpStorm.
 * User: Satyanarayan
 * Date: 03-06-2015
 * Time: 02:57
 */
?>
<style type="text/css">
    .profile-image{
        width:180px;
        height:200px;
        text-align: center;
        overflow: hidden;

    }
    .profile-image img{
        width:120%;
        height:100%;
        display: inline-block;
    }
    .profile-name{
        color:#0044cc;
    }


</style>
<div class="row border-bottom">
    <div class="col-lg-10">
            <div class="profile-name"><h1><?php echo $applicant_data->NAME;?></h1></div>
            <div class="row profile-contact-details">
                <div class="col-lg-12">
                    <!-- #557/3, 1<sup>st</sup> D Cross, 3<sup>rd</sup> Main,
                    Mathikere, Bangalore, Karnataka,<br/>
                    India - 560054. -->
                    <?php echo $applicant_data->ADDR;?>
                </div>
                <div class="col-lg-6"><br/>
                    <i class="fa fa-phone"></i> &nbsp;&nbsp;<strong><?php echo $applicant_data->CONTACT_NUMBER;?></strong><br/>
                    <i class="fa fa-envelope-o"></i> &nbsp;&nbsp;<strong><?php echo $applicant_data->EMAIL;?></strong><br/>
                    <i class="fa fa-bank"></i> &nbsp;&nbsp;<strong><?php echo $applicant_data->IBAN;?></strong>
                    <br/>
                    <br/>
                </div>
                <div class="col-lg-6"><br/>
                    <div class="col-lg-6">Driving Licence:</div><div class="col-lg-6"><a href="javascript:void(0);">Download</a> | <a href="javascript:void(0);">View</a></div>
                    <div class="col-lg-6">Hygiene Pass:</div><div class="col-lg-6"><a href="javascript:void(0);">Download</a> | <a href="javascript:void(0);">View</a></div>
                    <div class="col-lg-6">Other Doc:</div><div class="col-lg-6"><a href="javascript:void(0);">Download</a> | <a href="javascript:void(0);">View</a></div>
                    <br/>
                    <br/>
                </div>
            </div>
    </div>
    <div class="col-lg-2">
        <div class="profile-image border">
            <img src="<?php echo IMG_PATH.(($applicant_data->PROFILE_PIC)?'profiles/'.$applicant_data->PROFILE_PIC:'defaultProfile.png');?>" class="image-responsive">
        </div>
    </div>
</div>
<div class="row border-bottom">
    <div class="col-lg-12">
        <h2>Skills</h2>
        <p id="">
           <?php echo $applicant_data->SKILLS;?>
        </p>
    </div>
</div>
<div class="row border-bottom">
    <div class="col-lg-12">
        <h2>Description</h2>
        <p align="justify">
           <?php echo $applicant_data->DESCRIPTION;?>
        </p>
        <br/>
    </div>
</div>
<div class="row border-bottom">
    <div class="col-lg-12">
        <h2>Education</h2>
        <p align="justify">
            <ul>
                <li>Graduation | Some University | XXXX | </li>
                <li>Highschool</li>
                <li>School</li>
            </ul>
        </p>
        <br/>
    </div>
</div>
<div class="row border-bottom">
    <div class="col-lg-12">
        <h2>Experience</h2>
        <p align="justify">
            <ul>
                <li>Org1</li>
                <li>Org2</li>
                <li>Org3</li>
            </ul>
        </p>
        <br/>
    </div>
</div>
<div class="row"><br/>
    <div class="col-lg-12 center">
        <button type="button" class="btn btn-primary">Call for an Interview!</button>
        <button type="button" class="btn btn-info">Select Candidate!</button>
    </div>
</div>
<script type="text/javascript">
function getEducationdetails(){
    $.post('<?php echo SITE_PATH; ?>education/getempeducationdetails','',function(resp){
        bootbox.alert(resp);
           // document.getElementById('edu-details').innerHTML = resp;
    });
}
 
 
//getEducationdetails();

</script>