<?php
/**
 * Created by PhpStorm.
 * User: Satyanarayan
 * Date: 29-05-2015
 * Time: 16:02
 */
?>
 
<script type="text/javascript">
$(document).ready(function() {
    $('#jobfilter').multiselect({
        onChange: function(option, checked, select) {
           // alert('Changed option ' + $(option).val() + '.');
            $('#choosenfilters').append('<span class="badge badge-info">'+$(option).val()+'</span>');
        }
    });
    $('#skilfilter').multiselect({
        onChange: function(option, checked, select) {
            // alert('Changed option ' + $(option).val() + '.');
             $('#choosenfilters').append('<span class="badge badge-success">'+$(option).val()+'</span>');
         }
     });
});
      
    
</script>
<?php if(!isset($error_msg)){ ?>
<div class="panel-heading" style="margin-bottom:14px;">
                    <h2 style="width: 165px;">Basic Filter</h2>
    <span class="label label-primary">Jobs:</span>             
    <select id="jobfilter" multiple="multiple">
    <option value="cheese">Cheese</option>
    <option value="tomatoes">Tomatoes</option>
    <option value="mozarella">Mozzarella</option>
    <option value="mushrooms">Mushrooms</option>
    <option value="pepperoni">Pepperoni</option>
    <option value="onions">Onions</option>
</select>
<span class="label label-primary">Skills:</span>
   <select id="skilfilter" multiple="multiple">
    <option value="cheese">Cheese</option>
    <option value="tomatoes">Tomatoes</option>
    <option value="mozarella">Mozzarella</option>
    <option value="mushrooms">Mushrooms</option>
    <option value="pepperoni">Pepperoni</option>
    <option value="onions">Onions</option>
</select>
                </div>
<div class="panel-heading" >
<p id="choosenfilters"></p>
</div>
                <br>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Job Title</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Skills</th>
                        <th>Contact#</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach($records as $record){ ?>
                    <tr>
                        <td><?php echo $record->APPLIED_ON; ?></td>
                        <td><?php echo $record->JOB_TITLE; ?></td>
                        <td><?php echo $record->FIRST_NAME; ?></td>
                        <td><?php echo $record->LAST_NAME; ?></td>
                        <td><?php echo $record->SKILLS; ?></td>
                        <td><?php echo $record->CONTACT_NUM; ?></td>
                        <td><?php echo $record->EMAIL; ?></td>
                        <td><a href="<?php echo SITE_PATH?>profile/viewapplicantprofile/?w=<?php echo $record->WORKER_ID?>&j=<?php echo $record->JOB_ID?>"><i class="fa fa-search"></i></a></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
<?php }else{ ?>
    <div class="alert alert-danger"><?php echo $error_msg; ?></div>
<?php } ?>

