<?php
/**
 * Created by PhpStorm.
 * User: Satyanarayan
 * Date: 29-05-2015
 * Time: 16:02
 */
?>
<?php if(!isset($error_msg)){ ?>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Job Title</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Skills</th>
                        <th>Contact#</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach($records as $record){ ?>
                    <tr>
                        <td><?php echo $record->APPLIED_ON; ?></td>
                        <td><?php echo $record->JOB_TITLE; ?></td>
                        <td><?php echo $record->FIRST_NAME; ?></td>
                        <td><?php echo $record->LAST_NAME; ?></td>
                        <td><?php echo $record->SKILLS; ?></td>
                        <td><?php echo $record->CONTACT_NUM; ?></td>
                        <td><?php echo $record->EMAIL; ?></td>
                        <td><a href="<?php echo SITE_PATH?>profile/employee/?p=<?php echo $record->WRKR_ID?>"><i class="fa fa-eye"></i></a></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
<?php }else{ ?>
    <div class="alert alert-danger"><?php echo $error_msg; ?></div>
<?php } ?>

